In this notebook, I am going to expore two dataset: COVID-19 Vaccine Distribution Allocations by Jurisdiction - Pfizer and COVID-19 Vaccine Distribution Allocations by Jurisdiction - Moderna, also combine them together.

https://data.cdc.gov/Vaccinations/COVID-19-Vaccine-Distribution-Allocations-by-Juris/b7pe-5nws
https://data.cdc.gov/Vaccinations/COVID-19-Vaccine-Distribution-Allocations-by-Juris/saz5-9hgg

In [1]:
import pandas as pd

# <div align="center"> Data Dictionary

|Moderna Columns|Pfizer Columns|
|---|---|
|Jurisdiction|Jurisdiction|
|HHS Region|HHS Region|
||Doses allocated week of 12/14|
||Second Dose Shipment (21 days later) week of 12/14|
|Doses allocated week of 12/21|Doses allocated week of 12/21|
|Second Dose Shipment (28 days later) week of 12/21|Second Dose Shipment (21 days later) week of 12/21|
|Doses allocated week of 12/28|Doses allocated week of 12/28|
|Second Dose Shipment (28 days later) week of 12/28|Second Dose Shipment (21 days later) week of 12/28|
|Doses allocated for distribution week of 01/04|Doses allocated for distribution week of 01/04|
|Second dose shipment for distribution (28 days later) week of 01/04|Second dose shipment for distribution (21 days later) week of 01/04|
|Doses allocated for distribution week of 01/10|Doses allocated for distribution week of 01/10|
|Second dose shipment for distribution (28 days later) week of 01/10|Second dose shipment for distribution (21 days later) week of 01/10|
|Doses allocated for distribution week of 01/18|Doses allocated for distribution week of 01/18|
|Second dose shipment for distribution (28 days later) week of 01/18|Second dose shipment for distribution (21 days later) week of 01/18|
|Doses allocated for distribution week of 01/25|Doses allocated for distribution week of 01/25|
|Second dose shipment for distribution (28 days later) week of 01/25|Second dose shipment for distribution (21 days later) week of 01/25|
|Doses allocated for distribution week of 02/01|Doses allocated for distribution week of 02/01|
|Second dose shipment for distribution (28 days later) week of 02/01|Second dose shipment for distribution (21 days later) week of 02/21|
|Total Moderna Allocation "First Dose" Shipments|Total Pfizer Allocation "First Dose" Shipments|
|Total Allocation Moderna"Second Dose" Shipments|Total Allocation Pfizer "Second Dose" Shipments|

# COVID-19_Vaccine_Distribution_Allocations_by_Jurisdiction_-_Moderna.csv

In [2]:
vaccine_moderna=pd.read_csv('../data/COVID-19_Vaccine_Distribution_Allocations_by_Jurisdiction_-_Moderna.csv')

In [3]:
vaccine_moderna.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 18 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   Jurisdiction                                                         66 non-null     object
 1   HHS Region                                                           64 non-null     object
 2   Doses allocated week of 12/21                                        64 non-null     object
 3   Second Dose Shipment (28 days later) week of 12/21                   58 non-null     object
 4   Doses allocated week of 12/28                                        57 non-null     object
 5   Second Dose Shipment (28 days later) week of 12/28                   57 non-null     object
 6   Doses allocated for distribution week of 01/04                       64 non-null     object
 7   Second dose shipment for distribution (28 days later) week of 01/04  58 non-null     object
 8   Doses allocated for distribution week of 01/10                       57 non-null     object
 9   Second dose shipment for distribution (28 days later) week of 01/10  57 non-null     object
 10  Doses allocated for distribution week of 01/18                       57 non-null     object
 11  Second dose shipment for distribution (28 days later) week of 01/18  57 non-null     object
 12  Doses allocated for distribution week of 01/25                       57 non-null     object
 13  Second dose shipment for distribution (28 days later) week of 01/25  57 non-null     object
 14  Doses allocated for distribution week of 02/01                       64 non-null     object
 15  Second dose shipment for distribution (28 days later) week of 02/01  58 non-null     object
 16  Total Moderna Allocation "First Dose" Shipments                      65 non-null     object
 17  Total Allocation Moderna"Second Dose" Shipments                      65 non-null     object
dtypes: object(18)
memory usage: 9.4+ KB

In [4]:
vaccine_moderna.head()

,Jurisdiction,HHS Region,Doses allocated week of 12/21,Second Dose Shipment (28 days later) week of 12/21,Doses allocated week of 12/28,Second Dose Shipment (28 days later) week of 12/28,Doses allocated for distribution week of 01/04,Second dose shipment for distribution (28 days later) week of 01/04,Doses allocated for distribution week of 01/10,Second dose shipment for distribution (28 days later) week of 01/10,Doses allocated for distribution week of 01/18,Second dose shipment for distribution (28 days later) week of 01/18,Doses allocated for distribution week of 01/25,Second dose shipment for distribution (28 days later) week of 01/25,Doses allocated for distribution week of 02/01,Second dose shipment for distribution (28 days later) week of 02/01,"Total Moderna Allocation ""First Dose"" Shipments","Total Allocation Moderna""Second Dose"" Shipments"
0,Connecticut,Region 1,"63,300","63,300","21,900","21,900","21,800","21,800","21,900","21,900","23,000","23,000","23,000","23,000","30,300","30,300","205,200","205,200"
1,Maine,Region 1,"24,200","24,200","8,400","8,400","8,300","8,300","8,400","8,400","8,800","8,800","8,800","8,800","11,600","11,600","78,500","78,500"
2,Massachusetts,Region 1,"121,900","121,900","42,100","42,100","42,000","42,000","42,100","42,100","44,300","44,300","44,300","44,300","58,400","58,400","395,100","395,100"
3,New Hampshire,Region 1,"24,200","24,200","8,400","8,400","8,400","8,400","8,400","8,400","8,800","8,800","8,800","8,800","11,600","11,600","78,600","78,600"
4,Rhode Island,Region 1,"19,000","19,000","6,600","6,600","6,600","6,600","6,600","6,600","6,900","6,900","6,900","6,900","9,100","9,100","61,700","61,700"

In [5]:
vaccine_moderna.columns

Index(['Jurisdiction', 'HHS Region', 'Doses allocated week of 12/21',
       'Second Dose Shipment (28 days later) week of 12/21',
       'Doses allocated week of 12/28',
       'Second Dose Shipment (28 days later) week of 12/28',
       'Doses allocated for distribution week of 01/04',
       'Second dose shipment for distribution (28 days later) week of 01/04',
       'Doses allocated for distribution week of 01/10',
       'Second dose shipment for distribution (28 days later) week of 01/10',
       'Doses allocated for distribution week of 01/18',
       'Second dose shipment for distribution (28 days later) week of 01/18',
       'Doses allocated for distribution week of 01/25',
       'Second dose shipment for distribution (28 days later) week of 01/25',
       'Doses allocated for distribution week of 02/01',
       'Second dose shipment for distribution (28 days later) week of 02/01',
       'Total Moderna Allocation "First Dose" Shipments',
       'Total Allocation Moderna"Second Dose" Shipments'],
      dtype='object')

In [6]:
vaccine_moderna.shape

(66, 18)

> Checking if the total of the first doses are identical with the total of the second doses

In [7]:
total_first_not_equal_second=vaccine_moderna[vaccine_moderna["Total Moderna Allocation \"First Dose\" Shipments"]!=vaccine_moderna["Total Allocation Moderna\"Second Dose\" Shipments"]]
total_first_not_equal_second

,Jurisdiction,HHS Region,Doses allocated week of 12/21,Second Dose Shipment (28 days later) week of 12/21,Doses allocated week of 12/28,Second Dose Shipment (28 days later) week of 12/28,Doses allocated for distribution week of 01/04,Second dose shipment for distribution (28 days later) week of 01/04,Doses allocated for distribution week of 01/10,Second dose shipment for distribution (28 days later) week of 01/10,Doses allocated for distribution week of 01/18,Second dose shipment for distribution (28 days later) week of 01/18,Doses allocated for distribution week of 01/25,Second dose shipment for distribution (28 days later) week of 01/25,Doses allocated for distribution week of 02/01,Second dose shipment for distribution (28 days later) week of 02/01,"Total Moderna Allocation ""First Dose"" Shipments","Total Allocation Moderna""Second Dose"" Shipments"
54,American Samoa**,Region 9,"2,400",NaN,NaN,NaN,"2,400",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"3,200",NaN,"8,000",0
55,Guam**,Region 9,"7,600",NaN,NaN,NaN,"7,200",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"9,200",NaN,"24,000",0
56,Marshall Islands*,Region 9,"7,200",NaN,NaN,NaN,"6,400",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"6,600",NaN,"20,200",0
57,Micronesia*,Region 9,"9,800",NaN,NaN,NaN,"9,600",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"9,400",NaN,"28,800",0
58,Mariana Islands**,Region 9,"2,600",NaN,NaN,NaN,"2,400",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"3,200",NaN,"8,200",0
59,Palau*,Region 9,"2,800",NaN,NaN,NaN,"3,200",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"2,800",NaN,"8,800",0
64,Federal Entities ****,NaN,"298,200","289,200","100,000","100,000","108,400","99,600","99,900","99,900","105,000","105,000","105,000","105,000","149,400","138,600","965,900","937,300"
65,Total,NaN,"5,990,000","5,948,600","2,047,300","2,047,300","2,104,400","2,064,400","2,047,200","2,047,200","2,150,000","2,150,000","2,150,000","2,150,000","2,913,400","2,868,200",NaN,NaN

`from row 54 to 59 are islands far away from main land, so I am going to drop those rows.`

In [8]:
# drop rows that first total doses doesn't equal to the second total doses

vaccine_moderna.drop(total_first_not_equal_second.index.tolist(),inplace=True)

In [9]:
# drop all the second dose columns, since they all equal to the first dose
#https://stackoverflow.com/questions/19071199/drop-columns-whose-name-contains-a-specific-string-from-pandas-dataframe

vaccine_moderna=vaccine_moderna[vaccine_moderna.columns.drop
                                (list(vaccine_moderna.filter(regex='Second')))]

> replace all the punctuation for each cells

https://www.pythondaddy.com/python/how-to-remove-punctuation-from-a-dataframe-in-pandas-and-python/

In [10]:
def remove_punctuation(x):
    try:
        x=x.str.replace('[^\w\s]','')
    except:
        pass
    return x

In [11]:
vaccine_moderna=vaccine_moderna.apply(remove_punctuation)

<ipython-input-10-9a50bfdce9f6>:3: FutureWarning: The default value of regex will change from True to False in a future version.
  x=x.str.replace('[^\w\s]','')

> Nan value

In [12]:
# show rows with Nan value

vaccine_moderna[vaccine_moderna.isna().any(axis=1)]

,Jurisdiction,HHS Region,Doses allocated week of 12/21,Doses allocated week of 12/28,Doses allocated for distribution week of 01/04,Doses allocated for distribution week of 01/10,Doses allocated for distribution week of 01/18,Doses allocated for distribution week of 01/25,Doses allocated for distribution week of 02/01,"Total Moderna Allocation ""First Dose"" Shipments"
38,San Antonio,Region 6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
39,Houston,Region 6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
60,Alaska,Region 10,26800,NaN,25600,NaN,NaN,NaN,32300,84700

`San Antonio and Huston doesn't have any numbers, their doses are probably included in Taxes`

In [13]:
vaccine_moderna=vaccine_moderna.drop([38,39])

In [14]:
# fill out the rest of NaN value with 0

vaccine_moderna.fillna(0,inplace=True)

In [15]:
vaccine_moderna.shape

(56, 10)

In [16]:
vaccine_moderna.isnull().sum()

Jurisdiction                                       0
HHS Region                                         0
Doses allocated week of 12/21                      0
Doses allocated week of 12/28                      0
Doses allocated for distribution week of 01/04     0
Doses allocated for distribution week of 01/10     0
Doses allocated for distribution week of 01/18     0
Doses allocated for distribution week of 01/25     0
Doses allocated for distribution week of 02/01     0
Total Moderna Allocation "First Dose" Shipments    0
dtype: int64

> convert columns from object to interger

In [17]:
vaccine_moderna[['Doses allocated week of 12/21',
                'Doses allocated week of 12/28',
                'Doses allocated for distribution week of 01/04',
                'Doses allocated for distribution week of 01/10',
                'Doses allocated for distribution week of 01/18',
                'Doses allocated for distribution week of 01/25',
                'Doses allocated for distribution week of 02/01',
                'Total Moderna Allocation "First Dose" Shipments']]\
=vaccine_moderna[['Doses allocated week of 12/21',
                'Doses allocated week of 12/28',
                'Doses allocated for distribution week of 01/04',
                'Doses allocated for distribution week of 01/10',
                'Doses allocated for distribution week of 01/18',
                'Doses allocated for distribution week of 01/25',
                'Doses allocated for distribution week of 02/01',
                'Total Moderna Allocation "First Dose" Shipments']].astype('int64')

In [18]:
vaccine_moderna.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 56 entries, 0 to 63
Data columns (total 10 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Jurisdiction                                     56 non-null     object
 1   HHS Region                                       56 non-null     object
 2   Doses allocated week of 12/21                    56 non-null     int64
 3   Doses allocated week of 12/28                    56 non-null     int64
 4   Doses allocated for distribution week of 01/04   56 non-null     int64
 5   Doses allocated for distribution week of 01/10   56 non-null     int64
 6   Doses allocated for distribution week of 01/18   56 non-null     int64
 7   Doses allocated for distribution week of 01/25   56 non-null     int64
 8   Doses allocated for distribution week of 02/01   56 non-null     int64
 9   Total Moderna Allocation "First Dose" Shipments  56 non-null     int64
dtypes: int64(8), object(2)
memory usage: 4.8+ KB

In [19]:
# rename the Total Allocation column name for concat later

vaccine_moderna=vaccine_moderna.rename(columns={'Total Moderna Allocation "First Dose" Shipments':'Total Allocation "First Dose" Shipments'})

In [20]:
vaccine_moderna.head(1)

,Jurisdiction,HHS Region,Doses allocated week of 12/21,Doses allocated week of 12/28,Doses allocated for distribution week of 01/04,Doses allocated for distribution week of 01/10,Doses allocated for distribution week of 01/18,Doses allocated for distribution week of 01/25,Doses allocated for distribution week of 02/01,"Total Allocation ""First Dose"" Shipments"
0,Connecticut,Region 1,63300,21900,21800,21900,23000,23000,30300,205200

___

# COVID-19_Vaccine_Distribution_Allocations_by_Jurisdiction_-_Pfizer.csv

In [21]:
vaccine_pfizer=pd.read_csv('../data/COVID-19_Vaccine_Distribution_Allocations_by_Jurisdiction_-_Pfizer.csv')

In [22]:
vaccine_pfizer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 20 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   Jurisdiction                                                         66 non-null     object
 1   HHS Region                                                           64 non-null     object
 2   Doses allocated week of 12/14                                        61 non-null     object
 3   Second Dose Shipment (21 days later) week of 12/14                   58 non-null     object
 4   Doses allocated week of 12/21                                        57 non-null     object
 5   Second Dose Shipment (21 days later) week of 12/21                   57 non-null     object
 6   Doses allocated week of 12/28                                        57 non-null     object
 7   Second Dose Shipment (21 days later) week of 12/28                   57 non-null     object
 8   Doses allocated for distribution week of 01/04                       61 non-null     object
 9   Second dose shipment for distribution (21 days later) week of 01/04  58 non-null     object
 10  Doses allocated for distribution week of 01/10                       57 non-null     object
 11  Second dose shipment for distribution (21 days later) week of 01/10  57 non-null     object
 12  Doses allocated for distribution week of 01/18                       57 non-null     object
 13  Second dose shipment for distribution (21 days later) week of 01/18  57 non-null     object
 14  Doses allocated for distribution week of 01/25                       57 non-null     object
 15  Second dose shipment for distribution (21 days later) week of 01/25  57 non-null     object
 16  Doses allocated for distribution week of 02/01                       61 non-null     object
 17  Second dose shipment for distribution (21 days later) week of 02/21  58 non-null     object
 18  Total Pfizer Allocation "First Dose" Shipments                       65 non-null     object
 19  Total Allocation Pfizer "Second Dose" Shipments                      65 non-null     object
dtypes: object(20)
memory usage: 10.4+ KB

In [23]:
vaccine_pfizer.shape

(66, 20)

In [24]:
vaccine_pfizer.tail()

,Jurisdiction,HHS Region,Doses allocated week of 12/14,Second Dose Shipment (21 days later) week of 12/14,Doses allocated week of 12/21,Second Dose Shipment (21 days later) week of 12/21,Doses allocated week of 12/28,Second Dose Shipment (21 days later) week of 12/28,Doses allocated for distribution week of 01/04,Second dose shipment for distribution (21 days later) week of 01/04,Doses allocated for distribution week of 01/10,Second dose shipment for distribution (21 days later) week of 01/10,Doses allocated for distribution week of 01/18,Second dose shipment for distribution (21 days later) week of 01/18,Doses allocated for distribution week of 01/25,Second dose shipment for distribution (21 days later) week of 01/25,Doses allocated for distribution week of 02/01,Second dose shipment for distribution (21 days later) week of 02/21,"Total Pfizer Allocation ""First Dose"" Shipments","Total Allocation Pfizer ""Second Dose"" Shipments"
61,Idaho,Region 10,"13,650","13,650","9,750","9,750","12,675","12,675","9,750","9,750","9,750","9,750","10,725","10,725","10,725","10,725","10,725","10,725","87,750","87,750"
62,Oregon***,Region 10,"35,100","35,100","25,350","25,350","32,175","32,175","25,350","25,350","25,350","25,350","26,325","26,325","26,325","26,325","26,325","26,325","222,300","222,300"
63,Washington***,Region 10,"62,400","62,400","44,850","44,850","57,525","57,525","44,850","44,850","57,525","57,525","46,800","46,800","46,800","46,800","45,825","45,825","406,575","406,575"
64,Federal Entities ****,NaN,156000,142350,"102,375","102,375","128,700","128,700","117,000","101,400","102,375","102,375","105,300","105,300","105,300","105,300","119,925","104,325","936,975","892,125"
65,Total,NaN,"2,980,575","2,943,525","2,071,875","2,071,875","2,643,225","2,643,225","2,131,350","2,092,350","2,084,550","2,084,550","2,149,875","2,149,875","2,149,875","2,149,875","2,204,475","2,165,475",NaN,NaN

In [25]:
vaccine_pfizer.columns

Index(['Jurisdiction', 'HHS Region', 'Doses allocated week of 12/14',
       'Second Dose Shipment (21 days later) week of 12/14',
       'Doses allocated week of 12/21',
       'Second Dose Shipment (21 days later) week of 12/21',
       'Doses allocated week of 12/28',
       'Second Dose Shipment (21 days later) week of 12/28',
       'Doses allocated for distribution week of 01/04',
       'Second dose shipment for distribution (21 days later) week of 01/04',
       'Doses allocated for distribution week of 01/10',
       'Second dose shipment for distribution (21 days later) week of 01/10',
       'Doses allocated for distribution week of 01/18',
       'Second dose shipment for distribution (21 days later) week of 01/18',
       'Doses allocated for distribution week of 01/25',
       'Second dose shipment for distribution (21 days later) week of 01/25',
       'Doses allocated for distribution week of 02/01',
       'Second dose shipment for distribution (21 days later) week of 02/21',
       'Total Pfizer Allocation "First Dose" Shipments',
       'Total Allocation Pfizer "Second Dose" Shipments'],
      dtype='object')

> Total of the first doses are same as total of the second doses

In [26]:
total_first_not_equal_second_p=vaccine_pfizer[vaccine_pfizer["Total Pfizer Allocation \"First Dose\" Shipments"]!=vaccine_pfizer["Total Allocation Pfizer \"Second Dose\" Shipments"]]
total_first_not_equal_second_p

,Jurisdiction,HHS Region,Doses allocated week of 12/14,Second Dose Shipment (21 days later) week of 12/14,Doses allocated week of 12/21,Second Dose Shipment (21 days later) week of 12/21,Doses allocated week of 12/28,Second Dose Shipment (21 days later) week of 12/28,Doses allocated for distribution week of 01/04,Second dose shipment for distribution (21 days later) week of 01/04,Doses allocated for distribution week of 01/10,Second dose shipment for distribution (21 days later) week of 01/10,Doses allocated for distribution week of 01/18,Second dose shipment for distribution (21 days later) week of 01/18,Doses allocated for distribution week of 01/25,Second dose shipment for distribution (21 days later) week of 01/25,Doses allocated for distribution week of 02/01,Second dose shipment for distribution (21 days later) week of 02/21,"Total Pfizer Allocation ""First Dose"" Shipments","Total Allocation Pfizer ""Second Dose"" Shipments"
54,American Samoa**,Region 9,"5,850",NaN,NaN,NaN,NaN,NaN,"7,800",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"7,800",NaN,"21,450",0
55,Guam**,Region 9,"11,700",NaN,NaN,NaN,NaN,NaN,"7,800",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"7,800",NaN,"27,300",0
58,Mariana Islands**,Region 9,"5,850",NaN,NaN,NaN,NaN,NaN,"7,800",NaN,NaN,NaN,NaN,NaN,NaN,NaN,"7,800",NaN,"21,450",0
64,Federal Entities ****,NaN,156000,142350,"102,375","102,375","128,700","128,700","117,000","101,400","102,375","102,375","105,300","105,300","105,300","105,300","119,925","104,325","936,975","892,125"
65,Total,NaN,"2,980,575","2,943,525","2,071,875","2,071,875","2,643,225","2,643,225","2,131,350","2,092,350","2,084,550","2,084,550","2,149,875","2,149,875","2,149,875","2,149,875","2,204,475","2,165,475",NaN,NaN

In [27]:
# drop rows that first total doses doesn't equal to the second total doses

vaccine_pfizer.drop(total_first_not_equal_second_p.index.tolist(),inplace=True)

In [28]:
# drop all the second dose columns, since they all equal to the first dose
vaccine_pfizer=vaccine_pfizer[vaccine_pfizer.columns.drop
                              (list(vaccine_pfizer.filter(regex='Second')))]

> replace all the punctuation for each cells

In [29]:
vaccine_pfizer=vaccine_pfizer.apply(remove_punctuation)

<ipython-input-10-9a50bfdce9f6>:3: FutureWarning: The default value of regex will change from True to False in a future version.
  x=x.str.replace('[^\w\s]','')

> Nan value

In [30]:
# show rows with Nan value

vaccine_pfizer[vaccine_pfizer.isna().any(axis=1)]

,Jurisdiction,HHS Region,Doses allocated week of 12/14,Doses allocated week of 12/21,Doses allocated week of 12/28,Doses allocated for distribution week of 01/04,Doses allocated for distribution week of 01/10,Doses allocated for distribution week of 01/18,Doses allocated for distribution week of 01/25,Doses allocated for distribution week of 02/01,"Total Pfizer Allocation ""First Dose"" Shipments"
38,San Antonio,Region 6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
39,Houston,Region 6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
56,Marshall Islands,Region 9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
57,Micronesia,Region 9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
59,Palau,Region 9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
60,Alaska,Region 10,35100,NaN,NaN,27300,NaN,NaN,NaN,27300,89700

In [31]:
# drop everything except Alaska

vaccine_pfizer=vaccine_pfizer.drop([38,39,56,57,59])

In [32]:
# fill out the rest of NaN value with 0

vaccine_pfizer.fillna(0,inplace=True)

In [33]:
vaccine_pfizer.shape

(56, 11)

In [34]:
vaccine_pfizer.isnull().sum()

Jurisdiction                                      0
HHS Region                                        0
Doses allocated week of 12/14                     0
Doses allocated week of 12/21                     0
Doses allocated week of 12/28                     0
Doses allocated for distribution week of 01/04    0
Doses allocated for distribution week of 01/10    0
Doses allocated for distribution week of 01/18    0
Doses allocated for distribution week of 01/25    0
Doses allocated for distribution week of 02/01    0
Total Pfizer Allocation "First Dose" Shipments    0
dtype: int64

> convert columns from object to interger

In [35]:
vaccine_pfizer.columns

Index(['Jurisdiction', 'HHS Region', 'Doses allocated week of 12/14',
       'Doses allocated week of 12/21', 'Doses allocated week of 12/28',
       'Doses allocated for distribution week of 01/04',
       'Doses allocated for distribution week of 01/10',
       'Doses allocated for distribution week of 01/18',
       'Doses allocated for distribution week of 01/25',
       'Doses allocated for distribution week of 02/01',
       'Total Pfizer Allocation "First Dose" Shipments'],
      dtype='object')

In [36]:
vaccine_pfizer[['Doses allocated week of 12/14',
               'Doses allocated week of 12/21','Doses allocated week of 12/28',
       'Doses allocated for distribution week of 01/04',
       'Doses allocated for distribution week of 01/10',
       'Doses allocated for distribution week of 01/18',
       'Doses allocated for distribution week of 01/25',
       'Doses allocated for distribution week of 02/01',
       'Total Pfizer Allocation "First Dose" Shipments']]\
=vaccine_pfizer[['Doses allocated week of 12/14',
               'Doses allocated week of 12/21','Doses allocated week of 12/28',
       'Doses allocated for distribution week of 01/04',
       'Doses allocated for distribution week of 01/10',
       'Doses allocated for distribution week of 01/18',
        'Doses allocated for distribution week of 01/25',
        'Doses allocated for distribution week of 02/01',
       'Total Pfizer Allocation "First Dose" Shipments']].astype('int64')

In [37]:
vaccine_pfizer.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 56 entries, 0 to 63
Data columns (total 11 columns):
 #   Column                                          Non-Null Count  Dtype
---  ------                                          --------------  -----
 0   Jurisdiction                                    56 non-null     object
 1   HHS Region                                      56 non-null     object
 2   Doses allocated week of 12/14                   56 non-null     int64
 3   Doses allocated week of 12/21                   56 non-null     int64
 4   Doses allocated week of 12/28                   56 non-null     int64
 5   Doses allocated for distribution week of 01/04  56 non-null     int64
 6   Doses allocated for distribution week of 01/10  56 non-null     int64
 7   Doses allocated for distribution week of 01/18  56 non-null     int64
 8   Doses allocated for distribution week of 01/25  56 non-null     int64
 9   Doses allocated for distribution week of 02/01  56 non-null     int64
 10  Total Pfizer Allocation "First Dose" Shipments  56 non-null     int64
dtypes: int64(9), object(2)
memory usage: 5.2+ KB

In [38]:
# rename the Total Allocation column name for concat later

vaccine_pfizer=vaccine_pfizer.rename(columns={'Total Pfizer Allocation "First Dose" Shipments':'Total Allocation "First Dose" Shipments'})

In [39]:
vaccine_pfizer.head(1)

,Jurisdiction,HHS Region,Doses allocated week of 12/14,Doses allocated week of 12/21,Doses allocated week of 12/28,Doses allocated for distribution week of 01/04,Doses allocated for distribution week of 01/10,Doses allocated for distribution week of 01/18,Doses allocated for distribution week of 01/25,Doses allocated for distribution week of 02/01,"Total Allocation ""First Dose"" Shipments"
0,Connecticut,Region 1,31200,22425,28275,22425,22425,23400,23400,23400,196950

---

# Merge two data frame and clean more

## <div align="center"> data dictionary

|Column Name|Description|
|---|---|
|jurisdiction|States|
|hhs_region|U.S. Department of Health & Human Services Regions|
|doses_allocated_12_14|Doses allocated week of 12/14|
|doses_allocated_12_21|Doses allocated week of 12/21|
|doses_allocated_12_28|Doses allocated week of 12/28|
|doses_allocated_01_04|Doses allocated for distribution week of 01/04|
|doses_allocated_01_10|Doses allocated for distribution week of 01/10|
|doses_allocated_01_18|Doses allocated for distribution week of 01/18|
|doses_allocated_02_01|Doses allocated for distribution week of 02/01|
|total_first_allocation|Total Allocation "First Dose" Shipments from Pfizer and Moderna|

In [40]:
vaccine=pd.concat([vaccine_moderna,vaccine_pfizer]).groupby(['Jurisdiction','HHS Region']).sum().reset_index()
vaccine.head()

,Jurisdiction,HHS Region,Doses allocated week of 12/21,Doses allocated week of 12/28,Doses allocated for distribution week of 01/04,Doses allocated for distribution week of 01/10,Doses allocated for distribution week of 01/18,Doses allocated for distribution week of 01/25,Doses allocated for distribution week of 02/01,"Total Allocation ""First Dose"" Shipments",Doses allocated week of 12/14
0,Alabama,Region 4,113550,67125,58250,58350,60825,60825,70625,530500,40950.0
1,Alaska,Region 10,26800,0,52900,0,0,0,59600,174400,35100.0
2,Arizona,Region 9,161325,94925,83025,83225,86300,86300,100100,753700,58500.0
3,Arkansas,Region 6,69625,41100,36125,36225,37125,37125,43025,325700,25350.0
4,California,Region 9,905625,529675,463450,465325,485800,485800,562825,4226100,327600.0

In [41]:
# rename all the columns name for future convenience

vaccine=vaccine.rename(columns={
    'Jurisdiction':'jurisdiction',
    'HHS Region':'hhs_region',
    'Doses allocated week of 12/21':'doses_allocated_12_21',
    'Doses allocated week of 12/28':'doses_allocated_12_28',
    'Doses allocated for distribution week of 01/04':'doses_allocated_01_04',
    'Doses allocated for distribution week of 01/10':'doses_allocated_01_10',
    'Doses allocated for distribution week of 01/18':'doses_allocated_01_18',
    'Doses allocated for distribution week of 01/25':'doses_allocated_01_25',
    'Doses allocated for distribution week of 02/01':'doses_allocated_02_01',
    'Total Allocation "First Dose" Shipments':'total_first_allocation',
    'Doses allocated week of 12/14':'doses_allocated_12_14'
})

In [42]:
vaccine.columns

Index(['jurisdiction', 'hhs_region', 'doses_allocated_12_21',
       'doses_allocated_12_28', 'doses_allocated_01_04',
       'doses_allocated_01_10', 'doses_allocated_01_18',
       'doses_allocated_01_25', 'doses_allocated_02_01',
       'total_first_allocation', 'doses_allocated_12_14'],
      dtype='object')

In [43]:
# reset the oder of the columns

vaccine = vaccine.reindex(['jurisdiction','hhs_region','doses_allocated_12_14',
                           'doses_allocated_12_21','doses_allocated_12_28', 
                           'doses_allocated_01_04','doses_allocated_01_10', 
                           'doses_allocated_01_18','doses_allocated_01_25',
                           'doses_allocated_02_01','total_first_allocation'],axis=1)

In [44]:
vaccine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   jurisdiction            56 non-null     object
 1   hhs_region              56 non-null     object
 2   doses_allocated_12_14   56 non-null     float64
 3   doses_allocated_12_21   56 non-null     int64
 4   doses_allocated_12_28   56 non-null     int64
 5   doses_allocated_01_04   56 non-null     int64
 6   doses_allocated_01_10   56 non-null     int64
 7   doses_allocated_01_18   56 non-null     int64
 8   doses_allocated_01_25   56 non-null     int64
 9   doses_allocated_02_01   56 non-null     int64
 10  total_first_allocation  56 non-null     int64
dtypes: float64(1), int64(8), object(2)
memory usage: 4.9+ KB

In [45]:
# convert the doses_allocated_12_14 from float to interger

vaccine[['doses_allocated_12_14']]=vaccine[['doses_allocated_12_14']].astype('int64')

In [46]:
vaccine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56 entries, 0 to 55
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   jurisdiction            56 non-null     object
 1   hhs_region              56 non-null     object
 2   doses_allocated_12_14   56 non-null     int64
 3   doses_allocated_12_21   56 non-null     int64
 4   doses_allocated_12_28   56 non-null     int64
 5   doses_allocated_01_04   56 non-null     int64
 6   doses_allocated_01_10   56 non-null     int64
 7   doses_allocated_01_18   56 non-null     int64
 8   doses_allocated_01_25   56 non-null     int64
 9   doses_allocated_02_01   56 non-null     int64
 10  total_first_allocation  56 non-null     int64
dtypes: int64(9), object(2)
memory usage: 4.9+ KB

In [47]:
vaccine.head()

,jurisdiction,hhs_region,doses_allocated_12_14,doses_allocated_12_21,doses_allocated_12_28,doses_allocated_01_04,doses_allocated_01_10,doses_allocated_01_18,doses_allocated_01_25,doses_allocated_02_01,total_first_allocation
0,Alabama,Region 4,40950,113550,67125,58250,58350,60825,60825,70625,530500
1,Alaska,Region 10,35100,26800,0,52900,0,0,0,59600,174400
2,Arizona,Region 9,58500,161325,94925,83025,83225,86300,86300,100100,753700
3,Arkansas,Region 6,25350,69625,41100,36125,36225,37125,37125,43025,325700
4,California,Region 9,327600,905625,529675,463450,465325,485800,485800,562825,4226100

In [49]:
vaccine.to_csv('../data/vaccine_allocation.csv',index=False)